<?php
/**
 * Central metadata for all blog posts (link-earning content assets).
 *
 * Keyed by URL slug (file name without ".php"). The body/content lives in each
 * post stub (blog/<slug>.php); this file holds the listing metadata reused by
 * the post template, the blog hub, the sitemap and llms.txt.
 *
 * Fields: title, excerpt, date, updated, category, image, author, keywords
 */
require_once __DIR__ . '/../areas/areas-data.php';

function emp_posts() {
    return array(
        'moving-with-pets-india' => array(
            'title'    => 'Moving With Pets in India: How to Relocate Your Dog or Cat Safely',
            'excerpt'  => 'Relocating with a pet takes extra planning. Here is how to keep your dog or cat calm, safe and comfortable before, during and after a house move.',
            'date'     => '2026-06-24',
            'updated'  => '2026-06-24',
            'category' => 'Moving Tips',
            'image'    => '/excellent-Home-Relocation.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'moving with pets India, relocating with dog, moving with cat, pet relocation tips, house shifting with pets',
        ),
        'address-change-checklist-india' => array(
            'title'    => 'Address Change Checklist: What to Update After You Move in India',
            'excerpt'  => 'New home, new address. Use this checklist to update your Aadhaar, bank, gas, vehicle and other records so nothing important slips through after your move.',
            'date'     => '2026-06-24',
            'updated'  => '2026-06-24',
            'category' => 'Moving Tips',
            'image'    => '/best-packers-and-movers-in-visakhapatnam.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'address change checklist India, update Aadhaar address, change address after moving, post move checklist',
        ),
        'budget-moving-tips-1bhk' => array(
            'title'    => 'Moving on a Budget: How to Shift a 1BHK Without Overspending',
            'excerpt'  => 'Smart, practical ways to cut the cost of a small-home move in Visakhapatnam — from decluttering and timing to choosing the right service mix.',
            'date'     => '2026-06-24',
            'updated'  => '2026-06-24',
            'category' => 'Pricing',
            'image'    => '/Excellent-Storage-Solutions.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'budget moving tips, cheap house shifting 1BHK, save money moving, affordable packers and movers Visakhapatnam',
        ),
        'packing-materials-checklist' => array(
            'title'    => 'The Complete Packing Materials Checklist for a Smooth Move',
            'excerpt'  => 'Boxes, bubble wrap, tape and more — exactly what packing materials you need (and how much) to pack a home properly, room by room.',
            'date'     => '2026-06-24',
            'updated'  => '2026-06-24',
            'category' => 'Packing Tips',
            'image'    => '/Excellent-Packing-and-Unpacking.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'packing materials checklist, moving supplies list, packing boxes for moving, what you need to pack a house',
        ),
        'settling-into-new-home-checklist' => array(
            'title'    => 'Just Moved In? Your First-Week Checklist for a New Home',
            'excerpt'  => 'Unpacked the truck — now what? A practical first-week checklist to set up utilities, safety, essentials and your new neighbourhood after moving in.',
            'date'     => '2026-06-24',
            'updated'  => '2026-06-24',
            'category' => 'Moving Tips',
            'image'    => '/Excellent-Furniture-Assembly.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'settling into new home, first week after moving checklist, new home setup, post move tasks',
        ),
        'office-relocation-checklist-visakhapatnam' => array(
            'title'    => 'Office Relocation Checklist: Move Your Business in Visakhapatnam Without Downtime',
            'excerpt'  => 'A practical office shifting checklist for Visakhapatnam businesses — how to plan, pack IT and files, and relocate with minimal disruption to work.',
            'date'     => '2026-06-23',
            'updated'  => '2026-06-23',
            'category' => 'Office Moving',
            'image'    => '/Excellent-Office-Relocation.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'office relocation checklist Visakhapatnam, business shifting Vizag, commercial moving, office move planning',
        ),
        'how-to-pack-fragile-items' => array(
            'title'    => 'How to Pack Fragile Items for Moving: A Step-by-Step Guide',
            'excerpt'  => 'Glassware, crockery, electronics and mirrors need special care. Learn the materials and techniques professional packers use to move fragile items safely.',
            'date'     => '2026-06-22',
            'updated'  => '2026-06-22',
            'category' => 'Packing Tips',
            'image'    => '/Excellent-Packing-and-Unpacking.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'how to pack fragile items, packing glassware for moving, protect electronics moving, fragile packing tips',
        ),
        'mistakes-to-avoid-hiring-packers-movers' => array(
            'title'    => '10 Mistakes to Avoid When Hiring Packers and Movers',
            'excerpt'  => 'From skipping the written estimate to ignoring reviews, here are the ten most common (and costly) mistakes people make when hiring movers — and how to avoid them.',
            'date'     => '2026-06-21',
            'updated'  => '2026-06-21',
            'category' => 'Hiring Guide',
            'image'    => '/safe-packers-and-movers-in-visakhapatnam.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'mistakes hiring packers and movers, how to choose movers, avoid moving scams, hiring movers tips India',
        ),
        'car-bike-transportation-visakhapatnam' => array(
            'title'    => 'Car and Bike Transportation from Visakhapatnam: A Complete Guide',
            'excerpt'  => 'Shipping your vehicle? Learn how car and bike transportation works from Vizag, what it costs, the documents you need and how to hand over your vehicle safely.',
            'date'     => '2026-06-19',
            'updated'  => '2026-06-19',
            'category' => 'Vehicle Transport',
            'image'    => '/Excellent-Vehicle-Transportation.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'car transportation Visakhapatnam, bike transport Vizag, vehicle shifting, car carrier service Andhra Pradesh',
        ),
        'best-time-to-move-house-india' => array(
            'title'    => 'Best Time to Move House in India: Season, Day and Cost Tips',
            'excerpt'  => 'When you move affects both price and stress. Here is how season, month-end, weekends and even the time of day impact your move — and when to book for the best rate.',
            'date'     => '2026-06-18',
            'updated'  => '2026-06-18',
            'category' => 'Moving Tips',
            'image'    => '/excellent-Home-Relocation.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'best time to move house India, cheapest time to move, moving season, off peak moving discount',
        ),
        'moving-checklist-visakhapatnam' => array(
            'title'    => 'The Ultimate Moving Checklist for Relocating in Visakhapatnam',
            'excerpt'  => 'A week-by-week moving checklist to plan a smooth, stress-free home shift anywhere in Visakhapatnam — what to do 4 weeks, 1 week and 1 day before the move.',
            'date'     => '2026-06-20',
            'updated'  => '2026-06-20',
            'category' => 'Moving Tips',
            'image'    => '/excellent-Home-Relocation.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'moving checklist Visakhapatnam, home shifting checklist, relocation planning Vizag, packing checklist',
        ),
        'packers-movers-cost-visakhapatnam' => array(
            'title'    => 'How Much Do Packers and Movers Cost in Visakhapatnam? (2026 Price Guide)',
            'excerpt'  => 'Realistic 2026 price ranges for local and inter-state moves from Visakhapatnam, the factors that decide your cost, and how to avoid hidden charges.',
            'date'     => '2026-06-16',
            'updated'  => '2026-06-16',
            'category' => 'Pricing',
            'image'    => '/best-packers-and-movers-in-visakhapatnam.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'packers and movers cost Visakhapatnam, moving charges Vizag, house shifting price, relocation cost Andhra Pradesh',
        ),
        'monsoon-moving-tips-vizag' => array(
            'title'    => 'Moving During Monsoon in Visakhapatnam: 9 Tips to Keep Your Goods Safe',
            'excerpt'  => 'Vizag monsoons (June–September) make moving tricky. Here is how to waterproof your belongings, schedule smartly and protect electronics during a rainy-season move.',
            'date'     => '2026-06-10',
            'updated'  => '2026-06-10',
            'category' => 'Moving Tips',
            'image'    => '/Excellent-Packing-and-Unpacking.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'monsoon moving tips, rainy season relocation Visakhapatnam, waterproof packing, safe moving Vizag',
        ),
        'vizag-to-hyderabad-bangalore-moving-guide' => array(
            'title'    => 'Vizag to Hyderabad & Bangalore: Your Inter-State Moving Guide',
            'excerpt'  => 'Planning a long-distance move from Visakhapatnam to Hyderabad or Bangalore? Transit times, documents, costs and how to choose a reliable inter-state mover.',
            'date'     => '2026-06-04',
            'updated'  => '2026-06-04',
            'category' => 'Inter-State Moving',
            'image'    => '/Excellent-Vehicle-Transportation.jpeg',
            'author'   => 'Excellent Movers and Packers',
            'keywords' => 'Vizag to Hyderabad packers and movers, Visakhapatnam to Bangalore relocation, inter state moving guide, long distance movers',
        ),
    );
}
